dpu: lldb: Reduce amount of reading for alignement.
upmem/llvm-project pull request #103
Opened 2024-10-04 07:55 UTC by wwolff42

Writing to MRAM is quite tedious in the sense that address and size to MRAM must be aligned to 8 bytes.

Currently in LLDB, when writing, if address or size doesn't align to 8 bytes, we are reading the entire destination space with the constraint, and use some sort of masked data modification to finally rewrite the entire buffer back to the MRAM.

For example, taking `seqreader_example` regression test:

```
30: (lldb) memory write -i sample.bin `&buffer[0]`
30: 
30: ../../../../../work/dpu_tools/llvm-project/lldb/source/Plugins/Process/Dpu/ProcessDpu.cpp:642:WriteMemory(134217728, 0x55dc9e193400, 65501, )
30: ../../../../../work/dpu_tools/llvm-project/lldb/source/Plugins/Process/Dpu/Dpu.cpp:621:WriteMRAM(0, 0x55dc9e193400, 65501)
30: ../../../../../work/dpu_tools/llvm-project/lldb/source/Plugins/Process/Dpu/Dpu.cpp:622:WriteMRAM offset rem = 0, size rem = 5
30: ../../../../../work/dpu_tools/llvm-project/lldb/source/Plugins/Process/Dpu/Dpu.cpp:642:WriteMRAM slow path final_offset = 0, padding = 0, final_size = 65504
30: 
30: ../../../../../work/dpu_tools/llvm-project/lldb/source/Plugins/Process/Dpu/ProcessDpu.cpp:642:WriteMemory(134283229, 0x55dc9e144160, 39, )
30: ../../../../../work/dpu_tools/llvm-project/lldb/source/Plugins/Process/Dpu/Dpu.cpp:621:WriteMRAM(65501, 0x55dc9e144160, 39)
30: ../../../../../work/dpu_tools/llvm-project/lldb/source/Plugins/Process/Dpu/Dpu.cpp:622:WriteMRAM offset rem = 5, size rem = 7
30: ../../../../../work/dpu_tools/llvm-project/lldb/source/Plugins/Process/Dpu/Dpu.cpp:642:WriteMRAM slow path final_offset = 65496, padding = 5, final_size = 48
30: 65540 bytes were written to 0x8000000
```

LLDB internally dissect the write of 65540 bytes into two write of 65501 + 39 bytes.
Both LLDB write operation are not aligned. So in this case, we read 65504 + 48 from MRAM, update the buffer, and then write this same amount of data back to MRAM.

This patch implements a different approach by advancing the beggining and cropping the end to align them to 8 bytes, to then write a big aligned block.
On the same example as above, we only read 8 + 8 + 8 bytes for the alignement.

```
30: (lldb) memory write -i sample.bin `&buffer[0]`
30: 
30: ../../../../../work/dpu_tools/llvm-project/lldb/source/Plugins/Process/Dpu/ProcessDpu.cpp:642:WriteMemory(134217728, 0x56005774b3e0, 65501, )
30: ../../../../../work/dpu_tools/llvm-project/lldb/source/Plugins/Process/Dpu/ProcessDpu.cpp:660:WriteMemory locationInMRAM = 0
30: ../../../../../work/dpu_tools/llvm-project/lldb/source/Plugins/Process/Dpu/ProcessDpu.cpp:680:WriteMemory cropping sizeToAlignSize = 5
30: ../../../../../work/dpu_tools/llvm-project/lldb/source/Plugins/Process/Dpu/Dpu.cpp:621:WriteMRAM(65496, 0x56005775b3b8, 5)
30: ../../../../../work/dpu_tools/llvm-project/lldb/source/Plugins/Process/Dpu/Dpu.cpp:622:WriteMRAM offset rem = 0, size rem = 5
30: ../../../../../work/dpu_tools/llvm-project/lldb/source/Plugins/Process/Dpu/Dpu.cpp:642:WriteMRAM slow path final_offset = 65496, padding = 0, final_size = 8
30: ../../../../../work/dpu_tools/llvm-project/lldb/source/Plugins/Process/Dpu/ProcessDpu.cpp:688:WriteMemory new size = 65496
30: ../../../../../work/dpu_tools/llvm-project/lldb/source/Plugins/Process/Dpu/ProcessDpu.cpp:691:WriteMemory big aligned block locationInMRAM = 0, size = 65496
30: ../../../../../work/dpu_tools/llvm-project/lldb/source/Plugins/Process/Dpu/Dpu.cpp:621:WriteMRAM(0, 0x56005774b3e0, 65496)
30: ../../../../../work/dpu_tools/llvm-project/lldb/source/Plugins/Process/Dpu/Dpu.cpp:622:WriteMRAM offset rem = 0, size rem = 0
30: ../../../../../work/dpu_tools/llvm-project/lldb/source/Plugins/Process/Dpu/Dpu.cpp:631:WriteMRAM return fast path
30: 
30: ../../../../../work/dpu_tools/llvm-project/lldb/source/Plugins/Process/Dpu/ProcessDpu.cpp:642:WriteMemory(134283229, 0x5600576fc160, 39, )
30: ../../../../../work/dpu_tools/llvm-project/lldb/source/Plugins/Process/Dpu/ProcessDpu.cpp:660:WriteMemory locationInMRAM = 65501
30: ../../../../../work/dpu_tools/llvm-project/lldb/source/Plugins/Process/Dpu/ProcessDpu.cpp:667:WriteMemory advancing offsetToAlignLocation = 3
30: ../../../../../work/dpu_tools/llvm-project/lldb/source/Plugins/Process/Dpu/Dpu.cpp:621:WriteMRAM(65501, 0x5600576fc160, 3)
30: ../../../../../work/dpu_tools/llvm-project/lldb/source/Plugins/Process/Dpu/Dpu.cpp:622:WriteMRAM offset rem = 5, size rem = 3
30: ../../../../../work/dpu_tools/llvm-project/lldb/source/Plugins/Process/Dpu/Dpu.cpp:642:WriteMRAM slow path final_offset = 65496, padding = 5, final_size = 8
30: ../../../../../work/dpu_tools/llvm-project/lldb/source/Plugins/Process/Dpu/ProcessDpu.cpp:673:WriteMemory new locationInMRAM = 65504
30: ../../../../../work/dpu_tools/llvm-project/lldb/source/Plugins/Process/Dpu/ProcessDpu.cpp:674:WriteMemory new size = 36
30: ../../../../../work/dpu_tools/llvm-project/lldb/source/Plugins/Process/Dpu/ProcessDpu.cpp:680:WriteMemory cropping sizeToAlignSize = 4
30: ../../../../../work/dpu_tools/llvm-project/lldb/source/Plugins/Process/Dpu/Dpu.cpp:621:WriteMRAM(65536, 0x5600576fc183, 4)
30: ../../../../../work/dpu_tools/llvm-project/lldb/source/Plugins/Process/Dpu/Dpu.cpp:622:WriteMRAM offset rem = 0, size rem = 4
30: ../../../../../work/dpu_tools/llvm-project/lldb/source/Plugins/Process/Dpu/Dpu.cpp:642:WriteMRAM slow path final_offset = 65536, padding = 0, final_size = 8
30: ../../../../../work/dpu_tools/llvm-project/lldb/source/Plugins/Process/Dpu/ProcessDpu.cpp:688:WriteMemory new size = 32
30: ../../../../../work/dpu_tools/llvm-project/lldb/source/Plugins/Process/Dpu/ProcessDpu.cpp:691:WriteMemory big aligned block locationInMRAM = 65504, size = 32
30: ../../../../../work/dpu_tools/llvm-project/lldb/source/Plugins/Process/Dpu/Dpu.cpp:621:WriteMRAM(65504, 0x5600576fc163, 32)
30: ../../../../../work/dpu_tools/llvm-project/lldb/source/Plugins/Process/Dpu/Dpu.cpp:622:WriteMRAM offset rem = 0, size rem = 0
30: ../../../../../work/dpu_tools/llvm-project/lldb/source/Plugins/Process/Dpu/Dpu.cpp:631:WriteMRAM return fast path
30: 65540 bytes were written to 0x8000000
```

2024-10-04 08:03 UTC, wwolff42 commented
The commented `printf` and conditional will be removed before merge.
I keep them for review and discussion for now.

2024-10-04 08:29 UTC, wwolff42 commented
We could apply this approach to both WriteIRAM and WriteWRAM.

I will rework that to keep it simple in ProcessDPU, and add wrapper function on top of WriteMRAM, WriteIRAM and WriteWRAM.

2024-11-13 16:37 UTC, SylvanBrocard requested changes

2024-11-13 16:37 UTC, SylvanBrocard commented on lldb/source/Plugins/Process/Dpu/Dpu.cpp
> +  return this->WriteWRAMTreatingAlignement(offset, buf, size);
I assume everything after that is leftover debug? Or is this early return the debug state?

2024-11-13 16:37 UTC, SylvanBrocard commented on lldb/source/Plugins/Process/Dpu/Dpu.cpp
> +  // printf("%s:%d:%s(%u, %p, %zu)\n", __FILE__, __LINE__, __func__, offset, buf, size);
Let's do another review after the debug prints cleanup.

2024-11-13 16:37 UTC, SylvanBrocard commented on lldb/source/Plugins/Process/Dpu/Dpu.h
> +  bool WriteWRAMTreatingAlignement(uint32_t offset, const void *buf, size_t size);
Alignement -> Alignment

2024-11-13 16:37 UTC, SylvanBrocard commented on lldb/source/Plugins/Process/Dpu/Dpu.cpp
> +    const void *localBufPointer = (const char*)buf + pointerOffsetBuf + (size - sizeToAlignSize);
Use static_cast<const char*> over C-style cast
https://clang.llvm.org/extra/clang-tidy/checks/cppcoreguidelines/pro-type-cstyle-cast.html

2024-11-13 16:37 UTC, SylvanBrocard commented on lldb/source/Plugins/Process/Dpu/Dpu.cpp
> +    if (!this->WriteWRAMTreatingAlignement(locationInWRAM, buf, offsetToAlignLocation))
`this->` is unnecessary inside methods definition

2024-11-14 10:17 UTC, SylvanBrocard approved these changes

2024-11-14 12:51 UTC, placouture-upmem approved these changes
Approved, with suggestions about function naming and comments.

2024-11-14 12:51 UTC, placouture-upmem commented on lldb/source/Plugins/Process/Dpu/Dpu.cpp
> +bool Dpu::WriteWRAMTreatingAlignment(uint32_t offset, const void *buf, size_t size) {
I'm not sure that "Treating" is how English would put it. See https://www.linguee.com/english-french/translation/treat.html

2024-11-14 12:51 UTC, placouture-upmem commented on lldb/source/Plugins/Process/Dpu/Dpu.cpp
> +bool Dpu::WriteMRAMTreatingAlignment(uint32_t offset, const void *buf, size_t size) {
Same comment as above regarding the "Treating" term.

2024-11-14 12:51 UTC, placouture-upmem commented on lldb/source/Plugins/Process/Dpu/Dpu.cpp
> +bool Dpu::WriteMRAM(uint32_t offset, const void *buf, size_t size) {
Shouldn't we insert a doxygen-like function header comment, that explains shortly the processing difference between `Write[MW]RAM` and `Write[MW]RAMTreatingAlignment`?

Something like:

```
/**
 * @brief Write a buffer of bytes from SRAM to MRAM.
 * This function intends to use optimized write operations
 * for the part of the buffer that allows complete word-aligned read and
 * write operations
 * @param offset The offset of the first byte to be written to in MRAM
 * @buf The bytes buffer to be written from in SRAM
 * @size The number of bytes to be written
 * @return Whether the operation was succesful.
```

```
/**
 * @brief Write a buffer of bytes from SRAM to MRAM.
 * This function operates properly on buffers either word-aligned or not.
 * However, it does not attempt to fully optimize the write operations for
 * large buffers that are not properly word-aligned.
 * @param offset The offset of the first byte to be written to in MRAM
 * @buf The bytes buffer to be written from in SRAM
 * @size The number of bytes to be written
 * @return Whether the operation was succesful.
```

2024-11-15 13:19 UTC, merged